# -*- coding: utf-8 -*-
"""Copy of Unttled10.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1v0hqq_F2u5h1UJa9HwE1RhF1FChVULGZ

# ***Credit Card Fraud Detection***
"""

import pandas as pd

df = pd.read_csv("/content/creditcard.csv")
df.head()

"""**data exploration**




"""

fraud_percentage = df["Class"].value_counts( normalize = True )*100

print(fraud_percentage)

df['Amount'].describe()

"""**data preprocessing**

"""

x = df.drop ('Class', axis = 1)
y = df['Class']

from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
x[['Time','Amount']] = scaler.fit_transform(x[["Time",'Amount']])

from imblearn.over_sampling import SMOTE

smote = SMOTE(random_state = 42 )
x_resampled, y_resampled = smote.fit_resample(x,y)

"""**[EDA]**

*Histrogram*
"""

import matplotlib.pyplot as plt

df ['Amount'].hist(bins = 80)
plt.title('Amount Distrbution Transaction')

"""*Boxplots*"""

import seaborn as sus

sus.boxplot (x = 'Class',y = "Amount",data = df )

"""*Correlation* *Heatmap*"""

plt.figure(figsize = (12,8))
sus.heatmap (df.corr(),cmap = 'coolwarm',linewidths = 0.8)

"""**Feature**"""

from sklearn.ensemble import RandomForestClassifier

model= RandomForestClassifier(n_estimators=5, random_state=42)

model.fit(x_resampled,y_resampled)

importances = pd.Series(model.feature_importances_, index= x_resampled.columns)

importances.sort_values(ascending=False).head(10)

"""**Model Trainig **"""

from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report

X_train, X_test, y_train, y_test = train_test_split(
 x_resampled, y_resampled, test_size=0.2, random_state=42
)

lr = LogisticRegression(max_iter = 1000)
lr.fit(X_train, y_train)

y_pred = lr.predict(X_test)
print(classification_report(y_test,y_pred))

"""**Precision → How correct fraud predictions are**

**Recall → How many frauds we caught**

**F1-score → Balance of both**

**Accuracy → Overall correctness**
"""